spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: file:///C:\dev\code\IntelliJ\robotic-crustacean-config
          uri: https://github.com/battiloid/robotic-crustacean-config
          skipSslValidation: true
          timeout: 4
  security:
    user:
      name: configuser
      password: configPassword
      role: SYSTEM

server:
  port: 8888

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discuser:discPassword@eureka-peer1:8761/eureka
